spring:
  datasource:
    url: jdbc:h2:mem:qadb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-qa.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/